name: Read hello.txt

on:
  push:
    branches:
      - main

jobs:
  read-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read and Output
        run: cat hello.txt
        